version: '3.7'
services:
  moviekings:
    image: node:12
    container_name: moviekings
    volumes:
      - type: bind
        source: .
        target: /moviekingserver
      - type: volume
        source: node_modules
        target: /moviekingserver/node_modules
    working_dir: /moviekingserver
    command: >
      sh -c "yarn install --frozen-lockfile &&
             node index.js"
    ports:
    - "4000:4000"
volumes:
  node_modules:
